from app.db.database import get_conn, init_db
init_db()

TEXTO31 = '''[TEXTO: Since from August 1914 to November 1918 Great Britain and her Allies were fighting for civilization it cannot, I suppose, be impertinent to inquire what precisely civilization may be. Liberty and Justice have always been reckoned expensive words, but that Civilization could cost as much as I forget how many millions a day came as a surprise to many thoughtful taxpayers. The story of this word's rise to the highest place amongst British war aims is so curious that, even were it less relevant, I should be tempted to tell it. You are fighting for civilization, cried the wisest and best of those leaders who led us into war, and the very soldiers took up the cry, Join up, for civilization's sake. Startled by this sudden enthusiasm for an abstraction in which till then politicians and recruiting-sergeants had manifested little or no interest, I, in my turn, began to cry: And what is civilization? I did not cry aloud, be sure: at that time, for crying things of that sort aloud, one was sent to prison. But now that it is no longer criminal, nor unpatriotic even, to ask questions, I intend to inquire what this thing is for which we fought and for which we pay. I propose to investigate the nature of our leading war-aim. Whether my search will end in discovery and - if it does - whether what is discovered will bear any likeliness to the Treaty of Versailles remains to be seen. BELL, Clive. Civilization: An Essay. Penguin Books, 1938.]'''

TEXTO34 = '''[TEXTO: It is the standing reproach of a democratic society that it is the purgatory of genius and the paradise of mediocrity. With ourselves it has become notorious that when a man is so unfortunate as to exhibit uncommon abilities, he usually renders himself ineligible for political honors or distinctions. It would seem that the community is possessed with that groveling quality of a sordid mind which hates superiority, and would ostracize genius, as the Athenians did Aristides. One might believe it would not be unpleasing to the popular taste if some enterprising person could invent a machine for stunting intellectual development, after the fashion of idiotic barbarians who flatten the heads of their children. The masses of the community certainly appear to believe that political equality implies not only social, but should also imply intellectual equality, under pain of being severely frowned down by an outraged public opinion. The prevalent sentiment manifests itself in many different ways. It finds expression in public conveyances and resorts and is not altogether unknown even to the pulpit. It is found to perfection in the speeches of demagogues, who feel certain they are never so successful as when their audience is satisfied that the intellect of the speaker is of no higher an order than that of the lowest intelligence among them. Worse than all, it is demonstrated in the election of public officers of nearly all grades up to the highest: of which latter it has now become quite the custom to assume that it is impossible for a man of first-rate powers to be made President of the United States. The causes which lend to so singular a state of affairs are of an intricate and complex character. At the outset, it is difficult to realize the possibility of a system, the logical deduction from which appears to be that, if a man would rise in life, he must assiduously belittle his understanding. Perhaps it would be fairer to modify the proposition so far as to concede that ability is as useful here as elsewhere, provided the owner has the tact not to affront the sensibilities of the people by showing too much of it. No doubt a vague apprehension exists in the popular mind that shining talents are dangerous when intrusted with executive power in a republic: yet, it were a poor commentary on our institutions to intimate that, under them, for a man to be clever he must also be vicious. Experience rather teaches the contrary. If the diffusion of education, having the general tendency to elevate the understanding, is to produce more bad men than good, we had better abandon than foster our Common School system. Manifestly, we must look further for the solution of our enigma: that minds of moderate calibre ordinarily condemn everything which is beyond their range. THE NEW YORK TIMES. The worship of mediocrity. 17/08/1862.]'''

TEXTO37 = '''[TEXTO: When my family first moved to North Carolina, we lived in a rented house three blocks from the school where I would begin the third grade. My mother made friends with one of the neighbors, but one seemed enough for her. Within a year we would move again and, as she explained, there wasn't much point in getting too close to people we would have to say good-bye to. Our next house was less than a mile away, and the short journey would hardly merit tears or even good-byes, for that matter. It was more of a see you later situation, but still I adopted my mother's attitude, as it allowed me to pretend that not making friends was a conscious choice. I could if I wanted to. It just wasn't the right time. Back in New York State, we had lived in the country, with no sidewalks or streetlights; you could leave the house and still be alone. But here, when you looked out the window, you saw other houses, and people inside those houses. I hoped that in walking around after dark I might witness a murder, but for the most part our neighbors just sat in their living rooms, watching TV. The only place that seemed truly different was owned by a man named Mr. Tomkey, who did not believe in television. To say that you did not believe in television was different from saying that you did not care for it. Belief implied that television had a master plan and that you were against it. It also suggested that you thought too much. When my mother reported that Mr. Tomkey did not believe in television, my father said, Well, good for him. I don't know that I believe in it, either. That's exactly how I feel, my mother said, and then my parents watched the news, and whatever came on after the news. SEDARIS, David. Dress Your Family in Corduroy and Denim. Little, Brown and Company, 2004.]'''

QUESTOES = {
    31: (TEXTO31, 'A diferença existente entre os anos de 1914 a 1918 e o momento em que o texto foi escrito é que:'),
    32: ('', 'O termo startled, destacado no trecho do segundo parágrafo, Startled by this sudden enthusiasm [...], pode ser entendido como:'),
    33: ('', 'O termo likeliness, destacado no trecho do segundo parágrafo, [...] whether what is discovered will bear any likeliness to the Treaty of Versailles remains to be seen., pode ser substituído, sem prejuízo de significado, por:'),
    34: (TEXTO34, 'Leia atentamente as declarações destacadas. Em seguida, assinale a alternativa correta.'),
    35: ('', 'No trecho destacado, extraído do segundo parágrafo, It is found to perfection in the speeches of demagogues, who feel certain they are never so successful as when their audience is satisfied that the intellect of the speaker is of no higher an order than that of the lowest intelligence among them., a ideia principal é a de que:'),
    36: ('', 'De acordo com o terceiro parágrafo, é correto afirmar que:'),
    37: (TEXTO37, 'De acordo com o texto:'),
    38: ('', 'Os fatos apresentados pelo narrador no terceiro e no quarto parágrafos expressam:'),
    39: ('', 'O trecho destacado do segundo parágrafo, I hoped that in walking around after dark I might witness a murder, but for the most part our neighbors just sat in their living rooms, watching TV., poderia ser mais bem traduzido sem perda de sentido como:'),
    40: ('', 'O termo still, destacado no trecho do primeiro parágrafo, It was more of a see you later situation, but still I adopted my mother\'s attitude [...], transmite a ideia de:'),
}

conn = get_conn()
total = 0
for numero, (texto, enunciado) in QUESTOES.items():
    enunciado_final = texto + ' ' + enunciado if texto else enunciado
    rows = conn.execute('''
        SELECT id FROM questoes
        WHERE escola='ITA' AND ano=2021 AND fase='1'
        AND disciplina='ingles' AND numero=?
    ''', (numero,)).fetchall()
    for row in rows:
        conn.execute('UPDATE questoes SET enunciado=? WHERE id=?', (enunciado_final, row['id']))
        total += 1
        print(f'Q{numero}: atualizado')
conn.commit()
conn.close()
print(f'\nTotal: {total} atualizadas')
