from app.db.database import get_conn, init_db
init_db()

TEXTO1 = """[TEXTO: "In recent years, no more than a week goes by without news of a cosmic discovery worthy of banner headlines. While media gatekeepers may have developed an interest in the universe, this rise in coverage likely comes from a genuine increase in the public's appetite for science. Evidence for this abounds, from hit television shows inspired or informed by science, to the success of science fiction films starring marquee actors, and brought to the screens by celebrated producers and directors. And lately, theatrical release biopics featuring important scientists have become a genre unto itself. There's also widespread interest around the world in science festivals, science fiction conventions, and documentaries for television. The highest grossing film of all time is by a famous director who set his story on a planet orbiting a distant star. And it features a famous actress who plays an astrobiologist. While most branches of science have ascended in this era, the field of astrophysics persistently rises to the top. I think I know why. At one time or another every one of us has looked up at night sky and wondered: What does it all mean? How does it all work? And, what is my place in the universe?" — TYSON, Neil DeGrasse. Astrophysics for people in a hurry. United States of America: W. W. Norton & Company, Inc., 2017.]"""

TEXTO2 = """[TEXTO: What links Sir Isaac Newton, alien solar systems, and a new multi-million dollar TV show? The answer is "the three-body problem": a conundrum in astronomy and mathematics that describes why it's often difficult to predict the long-term trajectory of planets, moons and stars. So, what exactly is the problem? And how did it end up becoming the title of a TV series? To understand, you first need to know a bit about the background to the TV show, and its premise. The story is based on Liu Cixin's epic sci-fi trilogy, the Remembrance of Earth's Past, of which The Three-body Problem is the first book. The original trilogy is characterised by the author's attention to scientific detail. The adaptation is less so, but still crammed with scientific ideas. The TV series focuses on the "Oxford Five", who all studied under the same professor at the University of Oxford. Some have gone on to become scientists themselves (a postdoctoral physics researcher, a founder and chief scientific officer of a nano-tech company, and a theoretical physics academic), one has become a school physics teacher, while the fifth is now a snack-food entrepreneur. Scientific credentials abound. The crux of the story is that an alien race – called the Trisolarans or San-Ti Ren – is headed to Earth to colonise it. Through intergalactic communication, these travellers attempt to intimidate human scientists into slowing down our rapid technological advancement, making Earth easier to conquer. But why are these aliens so hell-bent on taking over our planet in the first place? This is where the three-body problem comes in. Bodies, in this context, is a scientific byword for planets, moons, suns or any other massive astronomical object. The extraterrestrials' home planet is situated in a solar system with three suns, hence their name in the English translation of the book – the Trisolarans. This three-sun system can be highly unstable, making conditions difficult for life, hence the desire to travel across the Universe in order to inhabit our relatively stable Solar System. We only have one Sun, so Earth's future is relatively predictable – at least for the next few million years. — YATES, Kit. BBC, 2024.]"""

TEXTO3 = """[TEXTO: The early development of radar was driven primarily by military imperatives, and the targets that were to be detected were mainly aircraft and ships. It was no surprise that echoes were also received from terrain and from rainstorms, but the discovery, during World War II, that birds were often detectable was less expected. As the technology developed, and specially after transmission at the shorter 'microwave' wavelengths became commonplace, echoes from insects were also identified. In the late 1940's and the 1950's, radar technology was adapted rapidly to the needs of meteorologists, while ornithologists pioneered the use of defence and air-traffic control radars to study bird migration. Radar observations of insects, however, were relatively sparse until the early 1960's, when radar meteorologists became rather intensely interested in a type of warm-weather echo that appeared, puzzlingly from their perspective, when there was not a cloud in sight. Perhaps spurred by the meteorologists' observations, entomologists began their own exploitation of the technology in 1968, when a rather modest radar, built by G.W. Schaefer specifically for insect observation and operated in West Africa just south of the Sahara, proved to be very effective. — DRAKE, V.A. and REYNOLDS, D.R. Radar Entomology: Observing Insect Flight and Migration. CAB Internacional, 2012.]"""

TEXTO4 = """[TEXTO: As scientists explore AI-written text, journals hammer out policies. Many ask authors to disclose use of ChatGPT and other generative artificial intelligence. "It's all we've been talking about since November," says Patrick Franzen, publishing director for SPIE, the international society for optics and photonics. He's referring to ChatGPT, the artificial intelligence (AI)-powered chatbot unveiled that month. In response to a prompt, ChatGPT can spin out fluent and seemingly well-informed reports, essays — and scientific manuscripts. Worried about the ethics and accuracy of such content, Franzen and managers at other journals are scrambling to protect the scholarly literature from a potential flood of manuscripts written in whole or part by computer programs. Some publishers have not yet formulated policies. Most of those that have avoid an outright ban on AI-generated text, but ask authors to disclose their use of the automated tools, as SPIE is likely to do. For now, editors and peer reviewers have few alternatives, as they lack enforcement tools. No software so far can consistently detect the synthetic text the majority of the time. In some cases, the resulting text is indistinguishable from what people would write. For example, researchers who read medical journal abstracts generated by ChatGPT failed to identify one-third of them as written by machine, according to a December 2022 preprint. AI developers are expected to create even more powerful versions, including ones trained specifically on scientific literature - a prospect that has sent a shock wave through the scholarly publishing industry. So far, scientists report playing around with ChatGPT to explore its capabilities, and a few have listed ChatGPT as a co-author on manuscripts. Publishing experts worry such limited use could morph into a spike of manuscripts containing substantial chunks of AI-written text. — BRAINARD, Jeffrey. Science, v. 379, n. 6634, p. 740-741, 22 fev. 2023.]"""

QUESTOES = {
    37: TEXTO1 + " De acordo com as informações encontradas no texto, é CORRETO afirmar que",
    38: TEXTO1 + " No excerto retirado do segundo parágrafo do texto, 'While most branches of science have ascended in this era, the field of astrophysics persistently rises to the top', o termo WHILE estabelece, entre as orações, a ideia de",
    39: TEXTO1 + " Na passagem do texto 'The highest grossing film of all time is by a famous director who set his story on a planet orbiting a distant star.', a expressão sublinhada pode ser traduzida como:",
    40: TEXTO2 + " According to the text, 'the three-body problem' in astronomy and mathematics can be described as",
    41: TEXTO2 + " According to the text, the TV series mentioned",
    42: TEXTO2 + " No excerto 'The extraterrestrials' home planet is situated in a solar system with three suns, hence their name in the English translation of the book – the Trisolarans. This three-sun system can be highly unstable, making conditions difficult for life, hence the desire to travel across the Universe in order to inhabit our relatively stable Solar System.', retirado do 5º parágrafo, o termo HENCE pode ser substituído em ambas as ocorrências, sem alteração de sentido, por",
    43: TEXTO3 + " De acordo com o texto, uma descoberta que causou surpresa aos usuários de radares durante a Segunda Guerra Mundial foi a capacidade do radar em detectar",
    44: TEXTO3 + " No excerto '... puzzlingly from their perspective, when there was not a cloud in sight.', retirado do 2º parágrafo, o termo PUZZLINGLY indica que os meteorologistas estavam diante de uma situação",
    45: TEXTO4 + " According to the text, some publishers of scientific journals are concerned about the",
    46: TEXTO4 + " Considerando o teor do artigo, assinale a tradução mais coerente para o título 'As scientists explore AI-written text, journals hammer out policies'.",
    47: TEXTO4 + " Leia as asserções destacadas e, em seguida, assinale a alternativa CORRETA.",
    48: TEXTO4 + " No trecho do último parágrafo do texto '... to explore its capabilities ...', o termo ITS refere-se a",
}

conn = get_conn()
total = 0
for numero, enunciado in QUESTOES.items():
    rows = conn.execute("""
        SELECT id FROM questoes
        WHERE escola='ITA' AND ano=2025 AND fase='1'
        AND disciplina='ingles' AND numero=?
    """, (numero,)).fetchall()
    for row in rows:
        conn.execute("UPDATE questoes SET enunciado=? WHERE id=?", (enunciado, row['id']))
        total += 1
        print(f"Q{numero}: atualizado")

conn.commit()
conn.close()
print(f"\nTotal: {total} questões atualizadas")
