from app.db.database import get_conn, init_db
init_db()

TEXTO31 = '''[TEXTO: Stupidity permeates our perception and practice of politics. We frequently accuse politicians, bureaucrats, journalists, voters, elites, and the masses for their stupidities. In fact, it is not only populist politicians, sensational journalism, and uneducated voters who are accused of stupidity. Similar accusations can be, and in fact have been, made concerning those who criticize them as well. It seems that stupidity is ubiquitous, unable to be contained within or attributed to one specific political position, personal trait, or even ignorance and erroneous reasoning. Undertaking a theoretical investigation of stupidity, Nabutaka Otobe challenges the assumption that stupidity can be avoided. The author argues that the very ubiquity of stupidity implies its unavoidability - that we cannot contain it in such domains as error, ignorance, or post-truth. What we witness is rather that one's reasoning can be sound, evidence-based, and stupid. In revealing this unavoidability, he contends that stupidity is an ineluctable problem not only of politics, but also of thinking. We become stupid because we think: it is impossible to distinguish a priori stupid thought from upright, righteous thought. Moreover, the failure to address the unavoidability of stupidity leads political theory to the failure to acknowledge the productive moments that experiences of stupidity harbor within. Such productive moments constitute the potential of stupidity - that radical new ideas can emerge out of our seemingly banal and stupid thinking in our daily political activity. Fonte: Routledge, 2020.]'''

TEXTO33 = '''[TEXTO: Jaap Wagelaar was my all-time favorite secondary school teacher. He gave me a 10/10 for my oral Dutch literature exam, taught psychoanalysis during grammar class, astounded pupils with odd puppet show performances during lunch breaks and sadly ended his career with a burn-out. Few students and fellow teachers understood him. But since I trusted his judgment like nobody else's, I once asked him why Piet Paaltjens and Gerard Reve, both canonized Dutch literary figures, albeit of very divergent genres, could occasionally be kind or ironic but were more often rather cynical, cold and heartless. The response he gave has stuck with me ever since: cynical people are in fact the most emotional ones. Because of their sentimentality they are unable to handle injustice and feel forced to build up a self-protective screen against painful emotions called cynicism. Irony is mild, harmless and green. Sarcasm is biting and represents an orange traffic light. And the color of cynicism is deep red, with the shape of a grim scar that hides a hurt soul. They are all equally beautiful. These words again came to my mind when thinking back on the dozens of ironic, sarcastic and cynical memes about underperforming politicians and policy scandals disseminated over the past year. Who has not seen the image of Donald Trump walking through a desolate, scorched forest mumbling to himself: My work here is almost done? Who has not read the scathing reports of Flemish Ministers Bart Somers and Hilde Crevits escaping from a window aided by an unidentified third person after a meeting of the Council of Ministers to avoid critical journalists with the defense that they urgently needed to go on holiday and windows are faster than doors? Who has not come across the video announcement for a fictitious thriller called Angstra Zeneca with Dutch Health Minister Hugo de Jonge exclaiming I have made it all a cancerous mess with a grimace stretching from ear to ear? And who has missed the most recent true story tragicomedy played by Charles Michel, male President of the European Council, and Ursula von der Leyen, female President of the European Commission, who had jointly been invited by Turkish President Recep Tayyip Erdogan to discuss the position of women in Turkey? Unfortunately, they were only offered one chair for two people, which was symbolically occupied by Michel who left Von der Leyen standing awkwardly for a while. She ended up settling for a place on the comfortable sofa reserved for second rank guests. It was damned easy to get addicted to these countless videos, photos, images and written parodies. Oh, did we have fun with them! Some were ironic, some sarcastic and others cynical, but they jointly sketch a disconcerting image of the quality and reputation of key politicians in liberal Western democracies. Fonte: EUR.nl, 2021.]'''

TEXTO35 = '''[TEXTO: In a new survey of North American Indian languages, Marianne Mithun gives an admirably clear statement of what is lost as each language ceases to be used. Speakers of these languages and their descendants are acutely aware of what it can mean to lose a language, she begins - and this is perfectly true, although these speakers must have taken the decision themselves not to teach the language to their children. It happens all too often - people regret that their language and culture are being lost but at the same time decide not to saddle their own children with the chore of preserving them. When a language disappears, the most intimate aspects of culture can disappear as well: fundamental ways of organizing experience into concepts, of relating ideas to each other, of interacting to people. The more conscious genres of verbal art are usually lost as well: traditional ritual, oratory, myth, legends, and even humor. Speakers commonly remark that when they speak a different language, they say different things and even think different thoughts. These are very interesting assertions. They slip by in a book on anthropological linguistics, where in a book on linguistic theory they would be highly contentious. Is it true that fundamental ways of organizing experience into concepts and of relating ideas to each other are specific to individual languages and are therefore likely to be lost when a language ceases to be used? Is it true that when speakers speak a different language, they say different things and even think different thoughts? Again, the extent to which thought depends on language is very controversial. These questions must be now faced, because only when we have reached an opinion on them will we be able to accept or reject Marianne Mithun's conclusion: The loss of a language represents a definitive separation of a people from its heritage. It also represents an irreparable loss for us all, the loss of opportunities to glimpse alternative ways of making sense of the human experience. Fonte: DALBY, Andrew. Language in danger. Columbia University Press, 2003.]'''

TEXTO38 = '''[TEXTO: Meritocracy has become a leading social ideal. Politicians across the ideological spectrum continually return to the theme that the rewards of life - money, power, jobs, university admission - should be distributed according to skill and effort. The most common metaphor is the even playing field upon which players can rise to the position that fits their merit. Conceptually and morally, meritocracy is presented as the opposite of systems such as hereditary aristocracy, in which one's social position is determined by the lottery of birth. Under meritocracy, wealth and advantage are merit's rightful compensation, not the fortuitous windfall of external events. And most people don't just think the world should be run meritocratically, they think it is meritocratic. However, although widely held, the belief that merit rather than luck determines success or failure in the world is demonstrably false. This is not least because merit itself is, in large part, the result of luck. Talent and the capacity for determined effort, sometimes called grit, depend a great deal on one's genetic endowments and upbringing. Perhaps more disturbing, simply holding meritocracy as a value seems to promote discriminatory behaviour. The management scholar Emilio Castilla at MIT and the sociologist Stephen Benard at Indiana University studied attempts to implement meritocratic practices, such as performance-based compensation in private companies. They found that, in companies that explicitly held meritocracy as a core value, managers assigned greater rewards to male employees over female employees with identical performance evaluations. This preference disappeared where meritocracy was not explicitly adopted as a value. This is surprising because impartiality is the core of meritocracy's moral appeal. The even playing field is intended to avoid unfair inequalities based on gender, race and the like. Yet Castilla and Benard found that, ironically, attempts to implement meritocracy leads to just the kinds of inequalities that it aims to eliminate. They suggest that this paradox of meritocracy occurs because explicitly adopting meritocracy as a value convinces subjects of their own moral sincerity. Satisfied that they are just, they become less inclined to examine their own behaviour for signs of prejudice. As with any ideology, part of its draw is that it justifies the status quo, explaining why people belong where they happen to be in the social order. It is a well-established psychological principle that people prefer to believe that the world is just. Fonte: BigThink, 2019.]'''

QUESTOES = {
    31: (TEXTO31, ' De acordo com o texto, é correto afirmar que Otobe'),
    32: ('', 'No trecho do segundo parágrafo what we witness is rather that one\'s reasoning can be sound, evidence-based, and stupid, o termo sublinhado RATHER expressa a ideia de'),
    33: (TEXTO33, ' De acordo com o texto, o professor Wagelaar'),
    34: ('', 'No trecho It was damned easy to get addicted to these countless videos, photos, images and written parodies, o adjetivo sublinhado DAMNED funciona como'),
    35: (TEXTO35, ' De acordo com o texto, Marianne Mithun afirma que'),
    36: ('', 'No trecho These questions must be now faced, because only when we have reached an opinion on them will we be able to accept or reject Marianne Mithun\'s conclusion, o termo sublinhado THEM refere-se a'),
    37: ('', 'No trecho The loss of a language represents a definitive separation of a people from its heritage, o termo sublinhado HERITAGE significa'),
    38: (TEXTO38, ' De acordo com o texto, a meritocracia'),
    39: ('', 'No trecho under meritocracy, wealth and advantage are merit\'s rightful compensation, not the fortuitous windfall of external events, o termo sublinhado FORTUITOUS significa'),
    40: ('', 'De acordo com o texto, o paradoxo da meritocracia ocorre porque'),
}

conn = get_conn()
total = 0
for numero, (texto, enunciado) in QUESTOES.items():
    enunciado_final = texto + enunciado if texto else enunciado
    rows = conn.execute('''
        SELECT id FROM questoes
        WHERE escola='ITA' AND ano=2022 AND fase='1'
        AND disciplina='ingles' AND numero=?
    ''', (numero,)).fetchall()
    for row in rows:
        conn.execute('UPDATE questoes SET enunciado=? WHERE id=?', (enunciado_final, row['id']))
        total += 1
        print(f'Q{numero}: atualizado')
conn.commit()
conn.close()
print(f'\nTotal: {total} atualizadas')
